// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzFeZOXxpxeaXS2Vglf3CTMz9iHwiurxQ',
    appId: '1:480239242836:web:9356f9e9e4796c112367c1',
    messagingSenderId: '480239242836',
    projectId: 'task-management-app-1516d',
    authDomain: 'task-management-app-1516d.firebaseapp.com',
    storageBucket: 'task-management-app-1516d.firebasestorage.app',
    measurementId: 'G-YHL4PC4ZRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbXLWnk6cvpWzz1xSUEkzkEuP-H-WrQwA',
    appId: '1:480239242836:android:ef840d835128d1ad2367c1',
    messagingSenderId: '480239242836',
    projectId: 'task-management-app-1516d',
    storageBucket: 'task-management-app-1516d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOosvM7IX09vFz4-MrRyiiDsEgLQEc5hc',
    appId: '1:480239242836:ios:3462908aab3540662367c1',
    messagingSenderId: '480239242836',
    projectId: 'task-management-app-1516d',
    storageBucket: 'task-management-app-1516d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOosvM7IX09vFz4-MrRyiiDsEgLQEc5hc',
    appId: '1:480239242836:ios:3462908aab3540662367c1',
    messagingSenderId: '480239242836',
    projectId: 'task-management-app-1516d',
    storageBucket: 'task-management-app-1516d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFeZOXxpxeaXS2Vglf3CTMz9iHwiurxQ',
    appId: '1:480239242836:web:2ea71a693301e1c82367c1',
    messagingSenderId: '480239242836',
    projectId: 'task-management-app-1516d',
    authDomain: 'task-management-app-1516d.firebaseapp.com',
    storageBucket: 'task-management-app-1516d.firebasestorage.app',
    measurementId: 'G-YSJVXDVWKS',
  );
}
